"""Seed the database with Atlanta parking lot data."""

from app.database import engine, SessionLocal, Base
from app.models import ParkingLot

ATLANTA_PARKING_LOTS = [
    # Large commercial garages
    {
        "name": "Georgia Pacific Parking Deck",
        "address": "133 Peachtree St NE, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 8.00,
        "website": "https://www.parkatlanta.com",
        "slot_count": 500,
        "occupied_count": 312,
        "latitude": 33.7590,
        "longitude": -84.3880,
    },
    {
        "name": "Centennial Olympic Park Garage",
        "address": "250 Park Ave W NW, Atlanta, GA 30313",
        "is_small_lot": False,
        "hourly_price": 15.00,
        "website": "https://www.centennialpark.com",
        "slot_count": 800,
        "occupied_count": 534,
        "latitude": 33.7607,
        "longitude": -84.3931,
    },
    {
        "name": "Five Points MARTA Parking",
        "address": "30 Alabama St SW, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 5.00,
        "website": "https://www.itsmarta.com",
        "slot_count": 350,
        "occupied_count": 280,
        "latitude": 33.7539,
        "longitude": -84.3916,
    },
    {
        "name": "Peachtree Center Parking",
        "address": "225 Peachtree St NE, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 12.00,
        "website": "https://www.peachtreecenter.com",
        "slot_count": 1200,
        "occupied_count": 876,
        "latitude": 33.7612,
        "longitude": -84.3870,
    },
    {
        "name": "CNN Center Parking Deck",
        "address": "190 Marietta St NW, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 18.00,
        "website": "https://www.cnncenter.com",
        "slot_count": 600,
        "occupied_count": 423,
        "latitude": 33.7588,
        "longitude": -84.3954,
    },
    {
        "name": "State Farm Arena Parking",
        "address": "1 State Farm Dr, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 20.00,
        "website": "https://www.statefarmarena.com",
        "slot_count": 900,
        "occupied_count": 145,
        "latitude": 33.7573,
        "longitude": -84.3963,
    },
    {
        "name": "Georgia World Congress Center Lot",
        "address": "285 Andrew Young Intl Blvd, Atlanta, GA 30313",
        "is_small_lot": False,
        "hourly_price": 15.00,
        "website": "https://www.gwcca.org",
        "slot_count": 1000,
        "occupied_count": 678,
        "latitude": 33.7605,
        "longitude": -84.3976,
    },
    {
        "name": "Underground Atlanta Garage",
        "address": "50 Upper Alabama St, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 10.00,
        "website": None,
        "slot_count": 400,
        "occupied_count": 198,
        "latitude": 33.7527,
        "longitude": -84.3903,
    },
    {
        "name": "Westin Peachtree Parking",
        "address": "210 Peachtree St NW, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 22.00,
        "website": "https://www.marriott.com",
        "slot_count": 450,
        "occupied_count": 390,
        "latitude": 33.7614,
        "longitude": -84.3875,
        },
    {
        "name": "Georgia State University Deck",
        "address": "55 Gilmer St SE, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 6.00,
        "website": "https://www.gsu.edu",
        "slot_count": 700,
        "occupied_count": 520,
        "latitude": 33.7530,
        "longitude": -84.3856,
    },
    {
        "name": "SunTrust Plaza Garage",
        "address": "303 Peachtree St NE, Atlanta, GA 30308",
        "is_small_lot": False,
        "hourly_price": 14.00,
        "website": None,
        "slot_count": 550,
        "occupied_count": 412,
        "latitude": 33.7635,
        "longitude": -84.3860,
    },
    {
        "name": "Tabernacle Parking Deck",
        "address": "152 Luckie St NW, Atlanta, GA 30303",
        "is_small_lot": False,
        "hourly_price": 10.00,
        "website": None,
        "slot_count": 300,
        "occupied_count": 145,
        "latitude": 33.7586,
        "longitude": -84.3925,
    },
    # Small independent lots
    {
        "name": "Sweet Auburn Lot",
        "address": "220 Auburn Ave NE, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 3.00,
        "website": None,
        "slot_count": 25,
        "occupied_count": 18,
        "latitude": 33.7557,
        "longitude": -84.3790,
    },
    {
        "name": "Edgewood Corner Parking",
        "address": "145 Edgewood Ave SE, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 4.00,
        "website": None,
        "slot_count": 20,
        "occupied_count": 12,
        "latitude": 33.7540,
        "longitude": -84.3830,
    },
    {
        "name": "Broad Street Parking",
        "address": "90 Broad St NW, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 5.00,
        "website": None,
        "slot_count": 15,
        "occupied_count": 10,
        "latitude": 33.7545,
        "longitude": -84.3910,
    },
    {
        "name": "Marietta Street Lot",
        "address": "310 Marietta St NW, Atlanta, GA 30313",
        "is_small_lot": True,
        "hourly_price": 3.50,
        "website": None,
        "slot_count": 30,
        "occupied_count": 22,
        "latitude": 33.7600,
        "longitude": -84.3990,
    },
    {
        "name": "Castleberry Hill Parking",
        "address": "180 Walker St SW, Atlanta, GA 30313",
        "is_small_lot": True,
        "hourly_price": 3.00,
        "website": None,
        "slot_count": 18,
        "occupied_count": 7,
        "latitude": 33.7498,
        "longitude": -84.3985,
    },
    {
        "name": "Woodruff Park Lot",
        "address": "91 Peachtree St NE, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 6.00,
        "website": None,
        "slot_count": 12,
        "occupied_count": 11,
        "latitude": 33.7561,
        "longitude": -84.3888,
    },
    {
        "name": "Lucky Street Parking",
        "address": "78 Luckie St NW, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 4.50,
        "website": None,
        "slot_count": 22,
        "occupied_count": 14,
        "latitude": 33.7580,
        "longitude": -84.3935,
    },
    {
        "name": "Mitchell Street Lot",
        "address": "65 Mitchell St SW, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 3.00,
        "website": None,
        "slot_count": 20,
        "occupied_count": 9,
        "latitude": 33.7510,
        "longitude": -84.3920,
    },
    {
        "name": "Spring Street Parking",
        "address": "200 Spring St NW, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 5.00,
        "website": None,
        "slot_count": 16,
        "occupied_count": 8,
        "latitude": 33.7595,
        "longitude": -84.3910,
    },
    {
        "name": "Forsyth Street Lot",
        "address": "45 Forsyth St NW, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 4.00,
        "website": None,
        "slot_count": 14,
        "occupied_count": 6,
        "latitude": 33.7550,
        "longitude": -84.3930,
    },
    {
        "name": "Decatur Street Parking",
        "address": "120 Decatur St SE, Atlanta, GA 30303",
        "is_small_lot": True,
        "hourly_price": 3.50,
        "website": None,
        "slot_count": 25,
        "occupied_count": 19,
        "latitude": 33.7525,
        "longitude": -84.3850,
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(ParkingLot).count()
        if existing > 0:
            print(f"Database already has {existing} lots. Skipping seed.")
            return
        for lot_data in ATLANTA_PARKING_LOTS:
            lot = ParkingLot(**lot_data)
            db.add(lot)
        db.commit()
        print(f"Seeded {len(ATLANTA_PARKING_LOTS)} parking lots.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
